" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" One of following
" Plug 'ctrlpvim/ctrlp.vim'
" Plug 'junegunn/fzf'
" Plug 'liuchengxu/vim-clap'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-dotenv'

" Requires
Plug 'guns/vim-sexp', {'for': 'clojure'}
Plug 'tpope/vim-sexp-mappings-for-regular-people', {'for': 'clojure'}
Plug 'liquidz/vim-iced', {'for': 'clojure'}
Plug 'luochen1990/rainbow', {'for': 'clojure'}
Plug 'liquidz/vim-iced-coc-source', {'for': 'clojure'}


Plug 'arcticicestudio/nord-vim'

Plug 'kana/vim-altercmd'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'lilydjwg/tailf.vim'

Plug 'dense-analysis/ale'

Plug 'tpope/vim-fugitive'

Plug 'diepm/vim-rest-console'

call plug#end()

syntax on
filetype plugin indent on

" group files nicely
set undodir=~/.vim/.undo//
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//

" global settings
let mapleader = "-"
let maplocalleader = "\\"
colorscheme nord

" make backspace work like you would expect in insert mode
set backspace=indent,eol,start

" massage tabs
set expandtab
set shiftwidth=4
set softtabstop=4

set rtp+=/usr/local/opt/fzf

" Enable vim-iced's default key mapping
" This is recommended for newbies
let g:iced_enable_default_key_mappings = v:true


let g:rainbow_active = 1 "set to 0 if you want to enable it later via :RainbowToggle


call altercmd#define('ls', 'Buffers')

nnoremap <leader>pp :<C-u>Files<CR>
nnoremap <leader>ps :<C-u>Ag<CR>

let g:ale_linters = {'clojure': ['joker']}
let g:ale_linters_explicit = 1
let g:ale_sign_column_always = 1

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()

autocmd BufNewFile,BufRead *.joke set filetype=clojure
autocmd BufNewFile,BufRead *.bb set filetype=clojure
autocmd FileType gitcommit setlocal spell textwidth=72
