export PATH="$(/usr/local/bin/brew --prefix coreutils)/libexec/gnubin:$PATH"
export MANPATH="$(/usr/local/bin/brew --prefix coreutils)/libexec/gnuman:$MANPATH"

export EDITOR="vim"
export PAGER="less -R"
export VISUAL="vim"
