#!/usr/bin/env zsh

export FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

autoload -Uz compinit && compinit
autoload -U colors && colors
autoload -Uz vcs_info

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# tab complete case insensitive
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

# history options
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE="$HOME/.history"
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY_TIME
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE

alias history='fc -l 1 | fzf'

zle -N zle-line-init
zle -N zle-keymap-select

eval "$(thefuck --alias)"

# vi mode
bindkey -v
export KEYTIMEOUT=1

setopt EXTENDED_GLOB

for srcfile in "${ZDOTDIR:-$HOME}"/.dotfiles/home/local-zsh/^README.md(N); do
  source "$srcfile"
done

# https://dougblack.io/words/zsh-vi-mode.html
function zle-line-init zle-keymap-select {
  VIM_PROMPT="%{$fg_bold[yellow]%}[% NORMAL]% %{$reset_color%}"
  CHECK=$(print -n "\u2714")
  GREEN_CHECK="%{$fg_bold[green]%}[$CHECK]%{$reset_color%}"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$EPS1"
  zle reset-prompt
}

WHITE_STAR="\u2606"
BLACK_STAR="\u2605"

export PS1="%(?.%{$fg_bold[blue]%}.%{$fg_bold[red]%})%~ %{$bg[bg_default]$fg[green]%}"$(print $BLACK_STAR)" %{$reset_color%}"

alias ls='eza'

###############
# git aliases #
###############
# rebase onto master
alias grbm='git rebase master'
# switch
alias gs='git switch'
alias gs-'git switch -'
# checkout
alias gc-='git co -'
alias gco='git co'
alias gcom='git co master'
alias gcb='git cob'
# status
alias gst='git status'
# pull
alias gp='git pull'
# log
alias gl='git log'
# commit
alias gci='git commit'

###-begin-codefresh-completions-###
#
# codefresh command completion script
#
# Installation: codefresh completion zsh >> ~/.zshrc
#
_codefresh_completions()
{
    type_list=($(codefresh --impl-zsh-file-dir --get-yargs-completions "${words[@]}"))

    if [[ ${type_list[1]} == '__files_completion__' ]]; then
        compadd -- "${type_list[@]:1}"
    else
        compadd -- "${type_list[@]}"
    fi

    return 0
}
compdef _codefresh_completions codefresh
###-end-codefresh-completions-###


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/mc mc
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
