#!/usr/bin/env zsh
export PS1="%(?.%{$fg_bold[white]%}.%{$fg_bold[red]%})%~ > %{$reset_color%}"

autoload -Uz compinit && compinit
autoload -U colors && colors
autoload -Uz vcs_info

precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
# git prompt helper
zstyle ':vcs_info:git:*' check-for-changes 'true'
zstyle ':vcs_info:git:*' stagedstr "S"
zstyle ':vcs_info:git:*' unstagedstr "*"
zstyle ':vcs_info:git:*' formats "%{$fg_bold[red]%}[%u%c]%{$reset_color%}%{$fg_bold[green]%}[%b]%{$reset_color%}"

# https://dougblack.io/words/zsh-vi-mode.html
function zle-line-init zle-keymap-select {
  VIM_PROMPT="%{$fg_bold[yellow]%}[% NORMAL]% %{$reset_color%}"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}${vcs_info_msg_0_/"[]"/}$EPS1"
  zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

eval "$(thefuck --alias)"

# vi mode
bindkey -v
export KEYTIMEOUT=1
